data:
  base_dir: ../Graph_Edge_Data
  test_loop_order: '9'
  train_loop_order:
  - '6'
  - '7'
  - '8'
  val: false
experiment:
  model_dir: models/train_6789_val_top_eigen_scalar_graphlet/7nza0ctf
  model_name: robust-sweep-196
  save_model: true
  seed: 42
  use_wandb: true
  wandb_name: rerun_robust-sweep-196
  wandb_project: train_6789_val_top_eigen_scalar_graphlet
features:
  selected_features:
  - eigen_1
  - eigen_2
  - eigen_3
  - graphlet_4
  - graphlet_3
  - degree
  - clustering
  - betweenness
  - pagerank
  - closeness
model:
  dropout: 0.3482800157275572
  hidden_channels: 16
  model_name: gin
  name: gin
  num_layers: 1
training:
  batch_size: 32
  epochs: 1
  learning_rate: 0.003867679571505464
  log_threshold_curves: false
  scheduler_type: none
  threshold: 0.5
  weight_decay: 1.361160248099375e-06
